// src/pages/Index.vue
<template>
  <Layout>
    <div class="articles mt-4 mx-auto bg-my-white p-4 rounded-lg">
      <h1 class="text-2xl font-bold">記事一覧</h1>
      <div class="mt-8">
        <article v-for="edge in $page.articles.edges" :key="edge.node.id">
          <h2 class="text-xl font-bold hover:opacity-60">
            <g-link :to="edge.node.path">{{ edge.node.title }}</g-link>
          </h2>
          <p class="mt-1 text-sm">{{ edge.node.createdAt }}</p>
          <div class="my-4">{{ edge.node.excerpt }}</div>
          <g-link :to="edge.node.path" class="border-b border-my-black hover:opacity-60">全文を読む→</g-link>
        </article>
      </div>
    </div>
  </Layout>
</template>

<page-query>
query fetchAllPost {
  articles: allArticle(sortBy: "createdAt") {
    edges {
      node {
        id
        content
        path
        title
        excerpt
        createdAt(format: "YYYY-MM-DD")
      }
    }
  }
}
</page-query>

<script>
export default {
  metaInfo: {
    title: '記事一覧'
  }
};
</script>

<style scoped>
.articles {
  max-width: 800px;
}

article:not(:first-of-type) {
  margin-top: 32px;
}
</style>

// pages/index.tsx
import { Layout } from '../components/Layout';
import { getArticles, Article } from '../utils/article';
import { InferGetStaticPropsType } from 'next';
import { useMemo } from 'react';

type ArticleWithExcerpt = Article & {
  excerpt: string;
};

const ArticlePreview = ({ article }: { article: ArticleWithExcerpt }) => {
  return (
    <article>
      <h2 className="text-xl font-bold hover:opacity-60">{article.title}</h2>
      <p className="mt-1 text-sm">{article.createdAt.toLocaleDateString()}</p>
      <div className="my-4">{article.excerpt}</div>
      <a className="border-b border-my-black hover:opacity-60">全文を読む→</a>
    </article>
  );
};

type IndexPageProps = InferGetStaticPropsType<typeof getStaticProps>;

const addExcerpt = (articles: Article[]): ArticleWithExcerpt[] => {
  return articles.map((article) => {
    const excerpt = article.content.slice(0, 256);
    return { ...article, excerpt };
  });
};

export default function IndexPage({ articles: parsedArticles }: IndexPageProps) {
  const articles = useMemo<ArticleWithExcerpt[]>(() => addExcerpt(parsedArticles), [parsedArticles]);

  return (
    <Layout>
      <div className="bg-white max-w-4xl mx-auto p-4 rounded-lg flex flex-col gap-8">
        {articles.map((article) => (
          <ArticlePreview article={article} key={article.title} />
        ))}
      </div>
    </Layout>
  );
}

export async function getStaticProps() {
  const articles = getArticles();

  return {
    props: { articles },
  };
}
